import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons
import qs.Ui

// The Omarcade cabinet: an upright arcade machine, one game at a time.
//
// Summoned from the marquee, or directly:
//   omarchy-shell shell summon ridgetopai.omarcade.cabinet '{}'
//
// ⚠️ PORTRAIT, AND THAT IS THE POINT. A real upright cabinet is taller
// than it is wide, and the parts stack the way the machine's do: the lit
// marquee on top, the screen in the middle, the control panel under your
// hands. The old landscape list was a settings panel that happened to be
// about games.
//
// ⚠️ ONE GAME AT A TIME, not a list. Arrow keys walk the aisle. A list
// shows you everything and invites nothing; a cabinet shows you one
// machine, big, with its screen lit.
//
// THE STYLE DIAL IS SET TO MODERN-FIRST (Brian, 2026-09-11): flat clean
// panels, crisp type, generous space. The 80s arrives through the
// SILHOUETTE, the accent glow on the marquee, and above all THE GAME ART
// — never through scanlines, a glass bezel, or a pixel font. Those read
// as a novelty skin, and this is meant to read as a product.
//
// Games are discovered from installed binaries rather than from score
// files, so a title that has never been played still appears — it just
// has nothing to beat yet.
Item {
  id: root

  // ---- host injections ----------------------------------------------
  property var shell: null
  property var manifest: null

  readonly property string pluginId:
    (manifest && manifest.id) ? manifest.id : "ridgetopai.omarcade.cabinet"

  // ---- theme ---------------------------------------------------------
  readonly property color foreground: Color.foreground
  readonly property color background: Color.background
  readonly property color accent: Color.accent

  // The cabinet body sits slightly off the window ground so the machine
  // reads as an object standing in the panel rather than as the panel.
  readonly property color panel: Qt.rgba(
    root.foreground.r * 0.06 + root.background.r * 0.94,
    root.foreground.g * 0.06 + root.background.g * 0.94,
    root.foreground.b * 0.06 + root.background.b * 0.94, 1.0)

  // The screen's surround. Near-black whatever the theme, because a
  // screen is a hole in the machine, not a painted panel.
  readonly property color bezel: Qt.rgba(
    root.background.r * 0.35, root.background.g * 0.35, root.background.b * 0.35, 1.0)

  readonly property string scoresDir:
    (Quickshell.env("XDG_STATE_HOME") || Quickshell.env("HOME") + "/.local/state")
    + "/omarcade/scores"

  readonly property string binDir: Quickshell.env("HOME") + "/.local/bin"

  // Where the committed cabinet art lives, next to this file.
  //
  // ⚠️ Generated by tools/make-cabinet-art.sh from each game's own
  // dump_frame — never screenshotted. A game with no art still works;
  // the screen falls back to its name on black, which is what an
  // unplayed cabinet in a dark arcade looks like anyway.
  readonly property string artDir: Qt.resolvedUrl("docs/cabinet")

  // ---- lifecycle -----------------------------------------------------

  function open(payloadJson) {
    scan()
    window.visible = true
    Qt.callLater(function () { if (keys) keys.forceActiveFocus() })
  }

  // Host-initiated close (`shell hide`): the shell already knows.
  function close() {
    window.visible = false
  }

  // User-initiated close (Esc, window button): tell the shell, or its
  // open-panel bookkeeping drifts and the next toggle does nothing.
  function requestClose() {
    if (shell && typeof shell.hide === "function") shell.hide(root.pluginId)
    else window.visible = false
  }

  // ---- discovery ------------------------------------------------------
  //
  // Installed binaries are the source of truth for "what can I play".
  // A find(1) over ~/.local/bin, so a second title needs no change here.

  property var games: []
  property int selected: 0

  Process {
    id: scanProc
    running: false
    command: ["find", root.binDir, "-maxdepth", "1", "-type", "f",
              "-name", "omarcade-*", "-printf", "%f\n"]

    stdout: StdioCollector {
      waitForEnd: true
      onStreamFinished: root.applyListing(text)
    }

    onExited: function (code) { if (code !== 0) root.games = [] }
  }

  function scan() {
    if (!scanProc.running) scanProc.running = true
  }

  function applyListing(output) {
    var found = []
    var lines = String(output || "").split("\n")
    for (var i = 0; i < lines.length; i++) {
      var name = lines[i].trim()
      if (name.length > 0) found.push(name)
    }
    found.sort()

    // Only reassign when the set changed, or the Instantiator rebuilds
    // every ScoreRecord and drops its file watches.
    if (JSON.stringify(found) !== JSON.stringify(root.games)) {
      root.games = found
      if (root.selected >= found.length) root.selected = 0
    }
  }

  // "omarcade-pixel-break" -> "Pixel Break". The score file carries a
  // proper display name; this is the fallback until one exists.
  //
  // ⚠️ EVERY WORD IS CAPITALISED. The old version title-cased only the
  // first, so a two-word id rendered "Pixel break" — latent since S1
  // because all three games ship a `name`, but it is the fallback for
  // every game that has never been played, which is exactly when a
  // cabinet is showing a title for the first time.
  function prettify(id) {
    var words = String(id).replace(/^omarcade-/, "").split(/[-_]+/)
    var out = []
    for (var i = 0; i < words.length; i++) {
      if (words[i].length === 0) continue
      out.push(words[i].charAt(0).toUpperCase() + words[i].slice(1))
    }
    return out.length ? out.join(" ") : id
  }

  // Bumped every time the set of ScoreRecords changes, so the bindings
  // below have something to DEPEND on.
  //
  // recordFor() is a plain function call: QML cannot see through it to
  // the Instantiator, so a binding that calls it is evaluated once and
  // never again. Assigning root.games fires the visual Repeater BEFORE
  // the Instantiator has built its objects — traced, and the order is
  // exactly that — so every row computed "not played yet" against a
  // null record and then froze that way forever, no matter what landed
  // on disk afterwards. Touching this property is what re-runs them.
  property int recordsRevision: 0

  function recordFor(index) {
    // objectAt, not itemAt: Instantiator hands back objects rather than
    // visual items.
    var r = records.objectAt(index)
    return r || null
  }

  function launch(index) {
    if (index < 0 || index >= games.length) return
    // uwsm-app puts the game in its own systemd scope: a crash stays the
    // game's problem instead of taking the shell down with it.
    Quickshell.execDetached(["uwsm-app", "--", root.binDir + "/" + games[index]])
    requestClose()
  }

  // Walk the aisle. Wraps, because an arcade row has no ends when you
  // are looking for something to play.
  function step(delta) {
    if (games.length === 0) return
    var next = (selected + delta) % games.length
    if (next < 0) next += games.length
    selected = next
  }

  // Instantiator, NOT Repeater.
  //
  // A Repeater creates its delegates as CHILDREN OF A VISUAL PARENT, and
  // this root Item has no size — the real UI lives in the FloatingWindow
  // below. So the delegates were never instantiated, itemAt() returned
  // null for every index, and every row read "not played yet" no matter
  // what was on disk. The marquee's identical-looking Repeater works
  // only because it sits inside a BarWidget that has real dimensions.
  //
  // Instantiator exists for exactly this: non-visual objects built from
  // a model, with no visual parent required.
  Instantiator {
    id: records
    model: root.games
    // Both signals matter: count changes when the game list changes,
    // and objectAdded fires as each record is actually built.
    onCountChanged: root.recordsRevision++
    onObjectAdded: root.recordsRevision++
    delegate: ScoreRecord {
      gameId: modelData
      path: root.scoresDir + "/" + modelData + ".json"
      // A record's file loading is also a reason to re-evaluate: the
      // object exists before its FileView has read anything.
      onRecordChanged: root.recordsRevision++
    }
  }

  // ---- the selected game, as the screen and the panel need it --------

  readonly property string currentId:
    (selected >= 0 && selected < games.length) ? games[selected] : ""

  readonly property string currentName: {
    root.recordsRevision
    var r = root.recordFor(root.selected)
    return (r && r.record && r.record.name) ? r.record.name : root.prettify(root.currentId)
  }

  // ---- window ---------------------------------------------------------

  FloatingWindow {
    id: window
    title: "Omarcade"
    color: root.background
    // ⚠️ PORTRAIT. A cabinet is taller than it is wide; the old 560x420
    // was landscape and fought the whole idea.
    //
    // ⚠️ A HYPRLAND SIZE RULE OVERRIDES THIS ENTIRELY — it is not a hint
    // the compositor weighs against anything. packaging/hyprland/omarcade.lua
    // pinned the cabinet to the old 560x420 for a while after the window
    // became portrait, and the result was a 560x720 hybrid: the width
    // from the rule, the height dragged back up by the minimum below.
    // The rule and these numbers are the same fact in two places; change
    // them together.
    implicitWidth: 640
    implicitHeight: 880
    // Tall enough that the screen keeps its 4:3 and the control panel
    // still has room for three difficulty rows. Below this the parts
    // start competing for the same pixels.
    minimumSize: Qt.size(480, 700)

    onVisibleChanged: if (!visible && !root.closingFromHost) root.requestClose()

    PanelKeyCatcher {
      id: keys
      anchors.fill: parent
      onCloseRequested: root.requestClose()
      onActivateRequested: root.launch(root.selected)
      onReturnRequested: root.launch(root.selected)
      // Both axes walk the aisle: left/right is the row, up/down is the
      // habit every list has taught. Refusing one of them would only be
      // a rule to learn.
      onMoveRequested: function (dx, dy) { root.step(dx !== 0 ? dx : dy) }

      // ---- the cabinet ------------------------------------------------

      Item {
        anchors.fill: parent
        anchors.margins: Style.space(18)

        // Empty state. A fresh install has games but the directory may
        // be missing entirely; say so rather than showing a dark box.
        Text {
          anchors.centerIn: parent
          width: parent.width - Style.space(40)
          visible: root.games.length === 0
          text: "No games found in ~/.local/bin.\n\nRun ./packaging/install.sh from the Omarcade repo."
          horizontalAlignment: Text.AlignHCenter
          wrapMode: Text.WordWrap
          color: Qt.darker(root.foreground, 1.4)
          font.family: Style.font.family
          font.pixelSize: Style.font.body
        }

        // ⚠️ THE PARTS ARE SIZED AS FRACTIONS OF THE CABINET, NOT IN
        // PIXELS. A first version fixed the marquee at 58px and the
        // control panel at 126px while the screen took its height from
        // the WIDTH (4:3). Rendered, the screen swallowed ~70% of the
        // machine, the marquee read as a titlebar rather than a sign,
        // the score rows were a cramped 10px strip, and a band of dead
        // space sat under the prompt. Everything below scales together.
        Column {
          id: stack
          anchors.fill: parent
          visible: root.games.length > 0

          // The fixed furniture, measured against the BASE spacing so
          // this cannot depend on `spacing` — which depends on it.
          readonly property int baseSpacing: Style.space(14)
          readonly property real furniture:
            marquee.height + titleRow.height + pips.height
            + panel.height + prompt.height + baseSpacing * 5

          // ⚠️ THE SCREEN CANNOT ALWAYS EAT THE SURPLUS, so something
          // else has to. It is capped at the art's 4:3, and once the
          // window is taller than that cap allows the leftover has
          // nowhere to go — it piled up as ~130px of dead space under
          // the prompt and the whole machine sat in the top two-thirds
          // of its window. Rendering at the true 640x880 showed it; at
          // the wrong 560x720 there was no surplus and it was invisible.
          //
          // Spread it through the joints instead, so the parts breathe
          // apart rather than the cabinet floating above a gap.
          //
          // ⚠️ `slack` is computed from the SCREEN'S CAP rather than from
          // its live height, and from `baseSpacing` rather than from
          // `spacing`. Both dodge a binding loop: spacing feeds furniture
          // feeds slack feeds spacing, and QML would either loop or
          // silently settle on whichever value it evaluated first.
          readonly property real screenCap:
            Math.min(Math.round(width * 3 / 4),
                     Math.max(Style.space(120), height - furniture))
          readonly property real slack:
            Math.max(0, height - furniture - screenCap)
          spacing: baseSpacing + Math.min(Style.space(22), slack / 6)

          // ---- THE MARQUEE ---------------------------------------------
          //
          // The lit sign on top of the machine, and the one place the
          // glow is allowed. Everything below it stays flat.
          Item {
            id: marquee
            width: parent.width
            // A real marquee is a substantial band across the top, not a
            // strip. Scaled so it keeps that presence at any size.
            height: Math.max(Style.space(54), Math.round(stack.height * 0.085))

            // The glow, as a stack of increasingly transparent rounded
            // rectangles behind the sign. No shader, no image: three
            // rectangles read as light and cost nothing.
            Repeater {
              model: 3
              Rectangle {
                required property int index
                anchors.centerIn: marqueePlate
                width: marqueePlate.width + (index + 1) * Style.space(7)
                height: marqueePlate.height + (index + 1) * Style.space(5)
                radius: height / 2
                color: "transparent"
                border.width: 1
                border.color: Qt.rgba(root.accent.r, root.accent.g, root.accent.b,
                                      0.13 / (index + 1))
              }
            }

            Rectangle {
              id: marqueePlate
              anchors.centerIn: parent
              width: parent.width
              height: parent.height
              radius: Style.space(8)
              color: Qt.rgba(root.accent.r, root.accent.g, root.accent.b, 0.10)
              border.width: 1
              border.color: Qt.rgba(root.accent.r, root.accent.g, root.accent.b, 0.45)

              Text {
                anchors.centerIn: parent
                text: "O M A R C A D E"
                color: root.foreground
                font.family: Style.font.family
                font.pixelSize: Style.font.heading
                font.bold: true
                // Wide tracking is the one typographic gesture that says
                // "marquee" without a novelty face.
                font.letterSpacing: Style.space(3)
              }
            }
          }

          // ---- THE SCREEN ----------------------------------------------
          //
          // 4:3, because every game in the suite renders 960x720 and a
          // real cabinet screen was 4:3 too. The art drops in with no
          // cropping and no letterboxing, now and for every future title.
          Rectangle {
            id: screenFrame
            // ⚠️ THE SCREEN TAKES WHAT IS LEFT, CAPPED AT 4:3. It is the
            // only flexible part, so it absorbs the difference at any
            // window size — but it never grows past the art's own aspect,
            // or a tall window would letterbox the picture inside a
            // screen that is mostly empty bezel.
            width: Math.min(parent.width, Math.round(available * 4 / 3))
            height: Math.min(Math.round(parent.width * 3 / 4), available)
            anchors.horizontalCenter: parent.horizontalCenter

            readonly property real available:
              Math.max(Style.space(120), stack.height - stack.furniture)

            radius: Style.space(6)
            color: root.bezel
            border.width: 1
            border.color: Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.10)
            clip: true

            // The art. Two Images cross-faded, so walking the aisle is a
            // dissolve rather than a blink.
            //
            // ⚠️ `fillMode: PreserveAspectFit` even though the aspects
            // match: it is the guarantee that a future game shipping art
            // at another size is letterboxed rather than stretched.
            Image {
              id: artA
              anchors.fill: parent
              anchors.margins: 1
              fillMode: Image.PreserveAspectFit
              smooth: false
              cache: true
              asynchronous: true
              opacity: 1
              Behavior on opacity { NumberAnimation { duration: 160 } }
            }

            Text {
              anchors.centerIn: parent
              width: parent.width - Style.space(40)
              horizontalAlignment: Text.AlignHCenter
              wrapMode: Text.WordWrap
              // Only when there is no art to show. A dark screen with the
              // title on it is what an unplayed cabinet looks like.
              visible: artA.status !== Image.Ready
              text: root.currentName
              color: Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.55)
              font.family: Style.font.family
              font.pixelSize: Style.font.title
              font.letterSpacing: Style.space(2)
            }
          }

          // ---- TITLE AND AISLE POSITION ---------------------------------
          Item {
            id: titleRow
            width: parent.width
            height: titleText.implicitHeight + Style.space(10)

            Text {
              id: leftArrow
              anchors.left: parent.left
              anchors.verticalCenter: parent.verticalCenter
              text: "◄"
              color: Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.45)
              font.pixelSize: Style.font.body
              visible: root.games.length > 1

              MouseArea {
                anchors.fill: parent
                anchors.margins: -Style.space(8)
                cursorShape: Qt.PointingHandCursor
                onClicked: root.step(-1)
              }
            }

            Text {
              id: titleText
              anchors.centerIn: parent
              text: root.currentName
              color: root.foreground
              font.family: Style.font.family
              font.pixelSize: Style.font.display
              font.bold: true
              font.letterSpacing: Style.space(1)
            }

            Text {
              anchors.right: parent.right
              anchors.verticalCenter: parent.verticalCenter
              text: "►"
              color: Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.45)
              font.pixelSize: Style.font.body
              visible: root.games.length > 1

              MouseArea {
                anchors.fill: parent
                anchors.margins: -Style.space(8)
                cursorShape: Qt.PointingHandCursor
                onClicked: root.step(1)
              }
            }
          }

          // The row of pips: which machine in the aisle. Reads at a
          // glance in a way "2 of 3" does not.
          Row {
            id: pips
            anchors.horizontalCenter: parent.horizontalCenter
            spacing: Style.space(6)
            height: Style.space(6)
            visible: root.games.length > 1

            Repeater {
              model: root.games

              Rectangle {
                required property int index
                width: index === root.selected ? Style.space(16) : Style.space(5)
                height: Style.space(5)
                radius: height / 2
                color: index === root.selected
                  ? root.accent
                  : Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.25)

                Behavior on width { NumberAnimation { duration: 140; easing.type: Easing.OutCubic } }
                Behavior on color { ColorAnimation { duration: 140 } }

                MouseArea {
                  anchors.fill: parent
                  anchors.margins: -Style.space(5)
                  cursorShape: Qt.PointingHandCursor
                  onClicked: root.selected = index
                }
              }
            }
          }

          // ---- THE CONTROL PANEL ----------------------------------------
          //
          // Where the scores live, under the screen, where your hands
          // would be. Flat — the marquee is the only thing that glows.
          Rectangle {
            id: panel
            width: parent.width
            // ⚠️ HEIGHT FROM ITS CONTENT, not a constant. A fixed 126px
            // was too tight for three difficulty rows at a readable size
            // and left dead space for a game with one.
            height: panelBody.implicitHeight + Style.space(28)
            radius: Style.space(8)
            color: root.panel
            border.width: 1
            border.color: Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.08)

            Column {
              id: panelBody
              anchors.left: parent.left
              anchors.right: parent.right
              anchors.verticalCenter: parent.verticalCenter
              anchors.margins: Style.space(14)
              spacing: Style.space(9)

              Text {
                text: "HIGH SCORES"
                color: Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.45)
                font.family: Style.font.family
                font.pixelSize: Style.font.caption
                font.letterSpacing: Style.space(2)
              }

              // Never played: say so plainly rather than showing zeroes,
              // which would look like a score you had earned.
              Text {
                width: parent.width
                visible: {
                  root.recordsRevision
                  var r = root.recordFor(root.selected)
                  return !r || r.best <= 0
                }
                text: "Not played yet"
                color: Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.5)
                font.family: Style.font.family
                font.pixelSize: Style.font.subtitle
              }

              // A single-tier game gets one big number. A tiered one gets
              // a row per difficulty, because an easy run and a hard run
              // are different games and collapsing them into one number
              // would quietly show whichever tier inflates it most.
              Text {
                visible: {
                  root.recordsRevision
                  var r = root.recordFor(root.selected)
                  return r && r.best > 0 && !r.isTiered
                }
                text: {
                  root.recordsRevision
                  var r = root.recordFor(root.selected)
                  return r ? String(r.best) : ""
                }
                color: root.foreground
                font.family: Style.font.family
                font.pixelSize: Style.font.displayLarge
                font.bold: true
              }

              Repeater {
                model: {
                  root.recordsRevision
                  var r = root.recordFor(root.selected)
                  return (r && r.best > 0 && r.isTiered) ? r.difficulties : []
                }

                Item {
                  required property string modelData
                  width: panelBody.width
                  height: Style.space(26)

                  Text {
                    anchors.left: parent.left
                    anchors.verticalCenter: parent.verticalCenter
                    text: modelData.toUpperCase()
                    color: Qt.rgba(root.foreground.r, root.foreground.g, root.foreground.b, 0.55)
                    font.family: Style.font.family
                    font.pixelSize: Style.font.body
                    font.letterSpacing: Style.space(1)
                  }

                  Text {
                    anchors.right: parent.right
                    anchors.verticalCenter: parent.verticalCenter
                    text: {
                      root.recordsRevision
                      var r = root.recordFor(root.selected)
                      if (!r) return ""
                      var by = r.bestByDifficulty
                      return by[modelData] !== undefined ? String(by[modelData]) : "—"
                    }
                    color: root.foreground
                    font.family: Style.font.family
                    font.pixelSize: Style.font.title
                    font.bold: true
                  }
                }
              }
            }
          }

          // ---- THE PROMPT -----------------------------------------------
          Text {
            id: prompt
            anchors.horizontalCenter: parent.horizontalCenter
            text: "▸  PRESS ENTER TO PLAY"
            color: Qt.rgba(root.accent.r, root.accent.g, root.accent.b, 0.85)
            font.family: Style.font.family
            font.pixelSize: Style.font.bodySmall
            font.letterSpacing: Style.space(2)

            // A slow pulse: the one piece of motion, and the thing a real
            // attract screen always did.
            SequentialAnimation on opacity {
              loops: Animation.Infinite
              running: window.visible
              NumberAnimation { from: 0.45; to: 1.0; duration: 1400; easing.type: Easing.InOutSine }
              NumberAnimation { from: 1.0; to: 0.45; duration: 1400; easing.type: Easing.InOutSine }
            }
          }
        }

        // Click anywhere on the screen to play the game showing on it.
        MouseArea {
          anchors.fill: screenFrame
          cursorShape: Qt.PointingHandCursor
          onClicked: root.launch(root.selected)
          enabled: root.games.length > 0
        }
      }
    }
  }

  // Point the screen at the selected game's art.
  //
  // ⚠️ A plain binding on `source` would reload the Image every time
  // `recordsRevision` ticked, which happens whenever any score file is
  // written — a flicker on the screen every time a game saves. Setting
  // it from a handler means it changes only when the SELECTION does.
  onCurrentIdChanged: {
    artA.source = root.currentId.length
      ? root.artDir + "/" + root.currentId.replace(/^omarcade-/, "") + ".png"
      : ""
  }

  property bool closingFromHost: false
}
